{% set version = "0.3-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plsdof
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/plsdof_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/plsdof/plsdof_{{ version }}.tar.gz
  sha256: 1718c9e05be6ad0114a6f02a6915a7cdee18b923dde9a0ec8624fa9f1c4a13af

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('plsdof')"           # [not win]
    - "\"%R%\" -e \"library('plsdof')\""  # [win]

about:
  home: https://github.com/fbertran/plsdof
  license: GPL (>= 2)
  summary: The plsdof package provides Degrees of Freedom estimates for Partial Least Squares (PLS) Regression. Model selection for PLS is based on various information criteria (aic, bic, gmdl) or on cross-validation. Estimates for the mean and covariance of the PLS regression coefficients are available. They allow the construction
    of approximate confidence intervals and the application of test procedures. Further, cross-validation procedures for Ridge Regression and Principal Components Regression are available.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: plsdof
# Type: Package
# Title: Degrees of Freedom and Statistical Inference for Partial Least Squares Regression
# Depends: MASS
# Version: 0.2-9
# Date: 2019-01-31
# Author: Nicole Kraemer, Mikio L. Braun
# Maintainer: Frederic Bertrand <frederic.bertrand@math.unistra.fr>
# Description: The plsdof package provides Degrees of Freedom estimates for Partial Least Squares (PLS) Regression. Model selection for PLS is based on various information criteria (aic, bic, gmdl) or on cross-validation. Estimates for the mean and covariance of the PLS regression coefficients are available. They allow the construction of approximate confidence intervals and the application of test procedures. Further, cross-validation procedures for Ridge Regression and Principal Components Regression are available.
# License: GPL (>= 2)
# LazyLoad: yes
# Packaged: 2019-01-31 17:51:20 UTC; fbertran
# NeedsCompilation: no
# Encoding: UTF-8
# Repository: CRAN
# Date/Publication: 2019-01-31 19:00:03 UTC
# RoxygenNote: 6.1.1
# URL: https://github.com/fbertran/plsdof
# BugReports: https://github.com/fbertran/plsdof/issues
