travis:
  secure:
    BINSTAR_TOKEN: AXmvsLaA2q5nGTLdWjz7tED8XUo1Ag9atCh9sYQIjI94pkpq24pInM0Zmjbo5WxzMR+4ncfntozyU20iESJjrIy1V+By1LeyLIdO9uhtFsEggjXTx2RSQhb2FWRoEoBDYeEVqAG9pV3IV6KnV7Jd5fdyHFE17S/SLTfThT9iSwaN1HaAnDFl23WPM4teHeWoFUev8hcdXreenx9Ufq2DEjLedJ+ltsl/KN4fBZU5xg7ReWzIEDpCF1vPDYD5Dfry/YTN5ZI8xiHB9wfJQSa7dKnUNM8h+lOAgRpDLyprIQ+SQ7QW3tP7A9eH4q6SYuVtJiNMn2Z6Voeqmb4n804JZ8nI/U9qcQWNbJNsxppbGntInqHoz8zF+KNdJfOG+COCbUILVKtbfrgy+Q9pPFc/kVatxx6exVY6yxZCUG0ZTFJ5VV79gIwZ7g3ecde5ACqAcfF4xDiDV+bT8nauTNAH4NmP14ahidG0S2RmcuebnZP6Y9vl0d8SvoMBAoIwWX947OZ5wA3R1ffpLjcR2urTIJj9AHik191QY4wXSwDC36WZD9fJJbAVovruBhgZD13+9H/b99lHxDCfjKy9q6abe0VNF2LelEZ9nOWkWaS941Y5JiiXLanJSoZ0GGIctl7gESoKjBWf4FyJn5bc0uVi9Y7gBv34+oEskGPjMmcGYG8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
