appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: UD7f1dIb2UecaebYh0cL4WwdnzRY9U4xFGb5AaDIPUCAcZCH3Sgb82s6XDJ15PGzBLL+zWW6mTtgWJ82+bTdSwNjnGFVm3VrJBhMybIntrY2XC1306BSSAoSW12Z4gE2RSJj02HS4sY5nnMxQ6cA6aSC0sdjD+FZiTZ/78KVV+EjmhayqTy255aYLfmv5ylnfFzKFAp0nqYg9JFDj+KEHjZBuyemL3ZtB9N9E1+d37yutH3dRuBRGSYbp+FhEaL735yyJML1IjftE03E7AHdjTCx5njgImA1CR1FYelmOAM4qo1bXyVzXdCCEjZL2wrEr8tmWiEDNIM9K+3A4FpVd0dE7U2xlMTFsQuFPSRxKZ0D8+A+8DAhP3TLR0QPTIElKDtbzxmZsfbmVd7AmnHZd55iaesHhuS1s5t+XJFtzg8v5JvV1Y2c9ad9jD6G2aYJ5zmFOWnAWXMQZJaWQXprieUEdleiGRvUVAkh20iBpRqim8uQMadfRsQF8CDeRIb+x+e6dIGhepmXA/mwIZDzMjQVntfqsJv2qYdbqxO3uVPV6Qbim9eOslBm2jC0MmqTHAi7xPtfOlKFnEUh30Dvr9t3CUJNaKxnh5b0xQ+GDel5fuFM0xf/orI1vatCPmfyq7Y09iUEiW8cQl7gwW5tSn0/plL/oSi7/59YL6UN9AE=}
bot:
  automerge: true
